import { useEffect, useRef, useState } from 'react';
import { milestones, periods } from '../history';
const pos=(n:number)=>((n+2000)/(new Date().getFullYear()+2000))*100;
export function Timeline({prediction,onRestart}:{prediction:string|null;onRestart:()=>void}){
 const [focus,setFocus]=useState<number|null>(800);const [explore,setExplore]=useState(false);const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!explore)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setExplore(false);trigger.current?.focus()}if(e.key==='Tab'){e.preventDefault();document.querySelector<HTMLButtonElement>('.history-modal .close')?.focus()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[explore]);
 return <section className="timeline-page"><div className="section-title"><span className="eyebrow">MISSION DISCOVERY / 03</span><h1>One timeline. <em>Many stories.</em></h1><p>The Maya story stretched across thousands of years.</p></div>
 <div className="timeline-board"><div className="timeline-label"><span>← EARLIEST</span><span>TIME MOVES FORWARD →</span></div><div className="axis">{[-2000,-1000,0,1000,2000].map(y=><span key={y} style={{left:`${pos(y)}%`}}>{y===0?'BC / AD':y<0?`${-y} BC`:y}</span>)}</div>
 <div className="maya-band"><b>MAYA CIVILIZATION</b><span>c. 2000 BC → living cultures today</span></div>
 <div className="period-rows">{periods.map(p=><button key={p.name} className={`period-row ${focus!==null&&focus>=p.start&&focus<=p.end?'highlight':''}`} onClick={()=>setFocus(p.name==='Roman world'?-31:p.name==='Viking Age'?800:p.start)}><span className="period-title">{p.name}<small>{p.label}</small></span><span className="period-track"><b style={{left:`${pos(p.start)}%`,width:`${Math.max(.6,pos(p.end)-pos(p.start))}%`}}/></span></button>)}{focus!==null&&<div className="time-line" style={{left:`calc(210px + (100% - 210px) * ${pos(focus)/100})`}}><span>{focus<0?`${-focus} BC`:`AD ${focus}`}</span></div>}</div>
 <div className="continuity">✦ Maya people and cultures continue today.</div></div>
 <div className="reveal-note"><span className="note-icon">↔</span><div><h2>{focus===800?'While Vikings sailed, Maya cities flourished.':focus===1485?'When the Tudor period began, Maya communities still lived in Mesoamerica.':focus===-31?'While Romans lived in Europe, Maya communities existed in Mesoamerica.':'Different places. Shared time.'}</h2><p>{focus===800&&prediction?`Your Viking prediction: “${prediction}”. The answer is YES. `:''}The Maya were not simply “before” these periods. Their histories overlapped.</p></div></div>
 <div className="timeline-actions"><button ref={trigger} className="secondary" onClick={()=>setExplore(!explore)}>{explore?'Close Maya history':'Explore the Maya through time'} <span>↗</span></button><button className="primary" onClick={onRestart}>Mission complete · Restart ↻</button></div>
 {explore&&<div className="modal-backdrop"><section className="modal history-modal" role="dialog" aria-modal="true" aria-label="Maya through time"><button className="close" autoFocus onClick={()=>{setExplore(false);trigger.current?.focus()}}>Close ✕</button><span className="eyebrow">A STORY THAT CONTINUES</span><h2>The Maya through time</h2><div className="milestones">{milestones.map(([date,text])=><div key={date}><b>{date}</b><p>{text}</p></div>)}</div></section></div>}
 </section>
}
